#' Custom ggplot theme
#'
#' Custom theme for ggplot
#' @export

theme_html = function (base_size = 9, base_family = "", font_size = 9,
  line_size = 0.5, rel_small = 12/14, rel_tiny = 11/14, rel_large = 18/14) {
  half_line = font_size/2
  small_size = rel_small * font_size
  theme(line = element_line(color = "black", size = 0.5, linetype = 1, lineend = "butt"),
        rect = element_rect(fill = NA, color = "black", size = 0.5, linetype = 1),
        text = element_text(family = base_family, face = "plain", color = "black",
                            size = base_size, lineheight = 0.9, hjust = 0.5, vjust = 0.5,
                            angle = 0, margin = margin(), debug = F),
        axis.line = element_blank(),
        #axis.line.x = NULL,
        axis.line.x = element_line(color = 'black', size = 0.5, lineend = 'square'),
        axis.line.y = NULL,
        axis.text = element_text(size = base_size * 1.1, color = "black"),
        axis.text.x = element_text(margin = margin(t = 0.8 * half_line/2), vjust = 1),
        axis.text.x.top = element_text(margin = margin(b = 0.8 * half_line/2), vjust = 0),
        axis.text.y = element_text(margin = margin(r = 0.8 * half_line/2), hjust = 1),
        axis.text.y.right = element_text(margin = margin(l = 0.8 * half_line/2), hjust = 0),
        axis.ticks = element_line(color = "black", size = 0.5),
        axis.ticks.length = unit(half_line / 1.75, "pt"),
        #axis.title.x = element_text(margin = margin(t = half_line), vjust = 1,
        #                            size = base_size * 1.3, face = "bold"),
        #axis.title.x.top = element_text(margin = margin(b = half_line), vjust = 0),
        #axis.title.y = element_text(angle = 90, margin = margin(r = half_line),
        #                            vjust = 1, size = base_size * 1.3, face = "bold"),
        #axis.title.y.right = element_text(angle = -90, vjust = 0,
        #                                  margin = margin(l = half_line/2)),
        axis.title.x = element_text(margin = margin(t = half_line/2), vjust = 1, size = base_size * 1.3), 
        axis.title.x.top = element_text(margin = margin(b = half_line/2), vjust = 0), 
        axis.title.y = element_text(angle = 90, margin = margin(r = half_line/2),
          vjust = 1, size = base_size * 1.3), 
        axis.title.y.right = element_text(angle = -90, margin = margin(l =
            half_line/2), vjust = 0), 
        legend.background = element_rect(color = NA),
        #legend.spacing = unit(0.4, "cm"),
        legend.spacing = unit(font_size, "pt"), 
        legend.spacing.x = NULL,
        legend.spacing.y = NULL,
        #legend.margin = margin(0.2, 0.2, 0.2, 0.2, "cm"),
        legend.margin = margin(0, 0, 0, 0), 
        #legend.key = element_rect(fill = "gray95", color = "white"),
        legend.key = element_blank(), 
        legend.key.size = unit(1.1 * font_size, "pt"),
        legend.key.height = NULL,
        legend.key.width = NULL,
        legend.text = element_text(size = rel(1)),
        legend.text.align = NULL,
        legend.title = element_text(hjust = 0, size = rel(1.1)),
        legend.title.align = NULL,
        legend.position = "right",
        legend.direction = NULL,
        legend.justification = "center",
        legend.box = NULL,
        legend.box.margin = margin(0, 0, 0, 0, "cm"),
        legend.box.background = element_blank(),
        legend.box.spacing = unit(0.4, "cm"),
        #panel.background = element_rect(fill = "white", color = NA),
        panel.background = element_blank(), 
        #panel.border = element_rect(color = "gray30", fill = NA, size = 0.7),
        panel.border = element_rect(color = "black", fill = NA, size = line_size * 1.75),
        panel.grid.major = element_line(color = "gray90", size = line_size * 1.5),
        panel.grid.minor = element_blank(),
        #panel.grid.minor = element_line(color = "gray90", size = 0.5,
        #                                linetype = "dashed"),
        panel.spacing = unit(base_size, "pt"),
        panel.spacing.x = NULL,
        panel.spacing.y = NULL,
        panel.ontop = F,
        #strip.background = element_rect(fill = "white", color = "gray30"),
        strip.background = element_rect(fill = 'gray30', color = 'gray30', 
          size = line_size * 3), 
        strip.text = element_text(color = "white", size = base_size * 1.25),
        strip.text.x = element_text(
          margin = margin(t = half_line * 0.3, b = half_line * 0.3)),
        strip.text.y = element_text(angle = -90, 
          margin = margin(l = half_line * 0.3, r = half_line * 0.3)),
        strip.placement = "inside",
        strip.placement.x = NULL,
        strip.placement.y = NULL,
        strip.switch.pad.grid = unit(0.1, "cm"),
        strip.switch.pad.wrap = unit(0.1, "cm"),
        plot.background = element_rect(color = NA),
        plot.title = element_text(size = rel(rel_large), hjust = 0.5,
                                  vjust = 1, face = "bold",
                                  margin = margin(b = half_line * 1.2)),
        plot.subtitle = element_text(size = base_size * 1.3, hjust = 0.5, vjust = 1,
                                     margin = margin(b = half_line * 0.9)),
        plot.caption = element_text(size = rel(0.9), hjust = 1, vjust = 1,
                                    margin = margin(t = half_line * 0.9)),
        plot.tag = element_text(size = rel(1.2), hjust = 0.5, vjust = 0.5),
        plot.tag.position = "topleft",
        plot.margin = margin(base_size, base_size, base_size, base_size), complete = T)
}
